version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: Rinha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./rinha-backend/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - rinha-network
    command: postgres -c max_connections=1000 -c max_wal_size=4096 -c checkpoint_timeout=600 -c synchronous_commit=off -c effective_cache_size=225MB -c shared_buffers=75MB -c fsync=off -c huge_pages=off -c work_mem=100MB -c maintenance_work_mem=256MB -c effective_io_concurrency=4

  rinha-backend-1:
    image: rinha-backend
    build:
      context: .
      dockerfile: rinha-backend/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=Rinha;Username=myuser;Password=mypassword
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"
    networks:
      - rinha-network

  rinha-backend-2:
    image: rinha-backend
    build:
      context: .
      dockerfile: rinha-backend/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=Rinha;Username=myuser;Password=mypassword
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"
    networks:
      - rinha-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - rinha-backend-1
      - rinha-backend-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge

volumes:
  postgres_data:
    name: my_postgres_data_volume
